name: Forex Analysis Agent

on:
  schedule:
    # Ejecutar diariamente a las 17:00 hora de España (UTC+1)
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  forex-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install playwright
        playwright install chromium
        playwright install-deps
        
    - name: Run Forex Agent
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: |
        python forex_mcp_agent.py
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: forex-analysis-results
        path: data/
        retention-days: 30 